behaviors:
  CarAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 40960
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0

      curiosity:
        strength: 0.05  # Incentiva l'esplorazione
        gamma: 0.99  
        encoding_size: 256  
        learning_rate: 3.0e-4  

    max_steps: 10000000
    time_horizon: 64
    summary_freq: 10000
